### PR TITLE
Added Resources section

### PR DESCRIPTION
**Pull request by packtpartner**
Added Resources section to feature external resources

### CODE REVIEW

**Comment by packtpartner** [comment]
@lirantal would it be appropriate to have a Resources section here?

**Comment by lirantal** [comment]
That seems fine yes, I'll merge it in.

**Comment by codydaig** [comment]
I'd rather see this at the bottom of the page. After they go through the steps we provide, then there's the additional resources for them to start diving in.

**Comment by packtpartner** [comment]
@codydaig thanks for the suggestion. It does make sense to have it at the end. Do you want it at the end of "Getting Started" or at the end of "AngularJS Menu Service"

**Pull request closed without merging**
