### PR TITLE
Updated resources.html

### PR DESCRIPTION
**Pull request by packtpartner**
Added a new video link under resources

### CODE REVIEW

**Comment by codydaig** [comment]
Looks like it worked!

**Comment by packtpartner** [comment]
Thanks @codydaig 
I still can't see the last video link on https://meanjs.org/docs.html#resources

**Comment by codydaig** [comment]
@packtpartner It's on the 0.4.x documentation where you made the PR too. 
https://meanjs.org/docs/0.4.x/#resources

**Comment by packtpartner** [comment]
Thanks for directing me to the right page @codydaig

**Pull request merged**
