### PR TITLE
Update resources.html

### PR DESCRIPTION
**Pull request by packtpartner**
Added a new book listing - MEAN Cookbook

### CODE REVIEW

**Comment by codydaig** [comment]
This looks to be a duplicate of the other PR, is that correct? And this one looks like proper formatting. Can you confirm?

**Comment by packtpartner** [comment]
Yes the old PR was not in the right format and this PR is with correct formatting. Thank You!

**Comment by packtpartner** [comment]
I was wondering if you could merge this PR

**Comment by packtpartner** [comment]
Could you please look into this PR
Thank you!

**Pull request closed without merging**
